modLoader="javafml" 
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Bithero-Studio/Sunken-Trinkets/issues"
license="LGPLv3"

[[mods]]
modId="losttrinkets"
version="${version}"
displayName="Sunken Trinkets"
displayURL="https://modrinth.com/mod/sunken-trinkets"
logoFile="logo.png"
logoBlur=false
authors="owmii,Mai-Lapyst"
description='''
70+ Unlockable trinkets with different useful abilities.
'''

[[dependencies.losttrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="architectury"
    mandatory=true
    versionRange="[2.10.12,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="cloth_config"
    mandatory=true
    versionRange="[5.3.63,]"
    ordering="NONE"
    side="BOTH"
