modLoader="javafml" 
loaderVersion="[34,)"
issueTrackerURL="https://github.com/owmii/lost-trinkets/issues"
license="LGPLv3"

[[mods]]
modId="losttrinkets"
version="${file.jarVersion}"
displayName="Lost Trinkets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lost-trinkets"
authors="owmii"
description='''
70+ Unlockable trinkets with different useful abilities.
'''

[[dependencies.losttrinkets]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.2,)"
    ordering="NONE"
    side="BOTH"