modLoader="javafml" 
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Bithero-Studio/Lost-Trinkets/issues"
license="LGPLv3"

[[mods]]
modId="losttrinkets"
version="${version}"
displayName="Lost Trinkets Rediscovered"
displayURL="https://modrinth.com/mod/lost-trinkets"
logoFile="logo.png"
logoBlur=false
authors="owmii,Mai-Lapyst"
description='''
70+ Unlockable trinkets with different useful abilities.
'''

[[dependencies.losttrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
    side="BOTH"