modLoader="javafml" 
loaderVersion="[33,)"
issueTrackerURL="https://github.com/owmii/losttrinkets/issues"
license="LGPLv3"

[[mods]]
modId="losttrinkets"
version="${file.jarVersion}"
displayName="Lost Trinkets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/losttrinkets"
authors="owmii"
description='''
70+ Unlockable trinkets with different useful abilities.
'''

[[dependencies.losttrinkets]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.3,)"
    ordering="NONE"
    side="BOTH"